mode = "repository"
name = "crystal-any"
repo = ["2::base",
	"2::base-openrc",
	"4::chrome-gnome-shell",
	"4::ckbcomp",
	"3::crystal-keyring",
	"2::filesystem",
	"2::gnome-apps-meta",
	"2::lsb-release",
	"4::mkinitcpio-openswap",
	"3::onyx",
	"1::citrine",
	"2::pfetch",
	"4::timeshift",
	"4::timeshift-autosnap",
	"3::wallpapers",
	"2::neofetch",
	"4::whitesur-icon-theme-git",
	"4::whitesur-cursor-theme-git",
	"4::whitesur-gtk-theme-git",
	"4::whitesur-kvantum-theme-git",
	"4::whitesur-kde-theme-git",
	"2::whitesur-grub-theme",
	"2::crystal-grub-theme",
	"4::flutter-group-pacman-hook",
	"4::flutter",
	"2::crystal-dev",
	"4::xviewer",
	"4::xplayer-plparser",
	"4::python-xdg",
	"4::xplayer",
	"4::pix",
	"4::iso-flag-png",
	"4::mintlocale",
	"4::mint-backgrounds-uma",
	"4::mint-themes",
	"4::mint-x-icons",
	"4::mint-y-icons",
	"4::mint-artwork-common",
	"2::cinnamon-meta",
]
urls = ["https://git.tar.black/crystal/programs/%repo%",
	"https://git.tar.black/crystal/pkgbuilds/%repo%",
	"https://git.tar.black/crystal/%repo%",
	"https://aur.archlinux.org/%repo%",
]
