mode = "repository"
name = "crystal-any"
repo = [
	"1::citrine",
	"1::crystal-keyring",
	"1::onyx",
	"1::wallpapers",
	"2::base",
	"2::cinnamon-meta",
	"2::crystal-dev",
	"2::crystal-grub-theme",
	"2::filesystem",
	"2::gnome-apps-meta",
	"2::lsb-release",
	"2::neofetch",
	"2::pfetch",
	"2::whitesur-grub-theme",
	"3::chrome-gnome-shell",
	"3::ckbcomp",
	"3::flutter",
	"3::flutter-group-pacman-hook",
	"3::iso-flag-png",
	"3::mint-artwork-common",
	"3::mint-backgrounds-uma",
	"3::mint-themes",
	"3::mint-x-icons",
	"3::mint-y-icons",
	"3::mintlocale",
	"3::mkinitcpio-openswap",
	"3::pix",
	"3::python-xdg",
	"3::timeshift",
	"3::timeshift-autosnap",
	"3::xplayer",
	"3::xplayer-plparser",
	"3::xviewer"
]
urls = [
	"https://github.com/crystal-linux/%repo%",
	"https://github.com/crystal-linux/pkgbuild.%repo%",
	"https://aur.archlinux.org/%repo%"
]
