mode = "repository"
name = "crystal-any"
repo = ["2::base",
	"4::chrome-gnome-shell",
	"4::ckbcomp",
	"3::crystal-keyring",
	"2::filesystem",
	"2::gnome-apps-meta",
	"2::lsb-release",
	"4::mkinitcpio-openswap",
	"3::onyx",
	"1::citrine",
	"2::pfetch",
	"4::timeshift",
	"4::timeshift-autosnap",
	"3::wallpapers",
	"2::neofetch",
	"4::whitesur-icon-theme-git",
	"4::whitesur-cursor-theme-git",
	"4::whitesur-gtk-theme-git",
	"4::whitesur-kde-theme-git",
]
urls = ["https://git.tar.black/crystal/programs/%repo%",
	"https://git.tar.black/crystal/pkgbuilds/%repo%",
	"https://git.tar.black/crystal/%repo%",
	"https://aur.archlinux.org/%repo%",
]
