[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-any"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"crs:crystal-keyring",
	"crs:onyx",
	"crs:wallpapers",
	"pkg:base",
	"pkg:crystal-dev",
	"pkg:crystal-grub-theme",
	"pkg:filesystem",
	"pkg:lsb-release",
	"pkg:neofetch",
	"pkg:pfetch",
	"pkg:pkg-warner",
	"aur:timeshift",
	"aur:timeshift-autosnap",
]

[repositories.urls]
crs = "https://github.com/crystal-linux/{}"
pkg = "https://github.com/crystal-linux/pkgbuild.{}"
aur = "https://aur.archlinux.org/{}"
