[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-any"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"crs:citrine",
	"crs:crystal-keyring",
	"crs:onyx",
	"crs:wallpapers",
	"pkg:base",
	"pkg:cinnamon-meta",
	"pkg:crystal-dev",
	"pkg:crystal-grub-theme",
	"pkg:filesystem",
	"pkg:gnome-apps-meta",
	"pkg:lsb-release",
	"pkg:neofetch",
	"pkg:pfetch",
	"pkg:pkg-warner",
	"aur:chrome-gnome-shell",
	"aur:ckbcomp",
	"aur:flutter",
	"aur:flutter-group-pacman-hook",
	"aur:iso-flag-png",
	"aur:mint-artwork-common",
	"aur:mint-backgrounds-uma",
	"aur:mint-themes",
	"aur:mint-x-icons",
	"aur:mint-y-icons",
	"aur:mintlocale",
	"aur:mkinitcpio-openswap",
	"aur:pix",
	"aur:python-xdg",
	"aur:timeshift",
	"aur:timeshift-autosnap",
	"aur:xplayer",
	"aur:xplayer-plparser",
	"aur:xviewer"
]

[repositories.urls]
crs = "https://github.com/crystal-linux/{}"
pkg = "https://github.com/crystal-linux/pkgbuild.{}"
aur = "https://aur.archlinux.org/{}"
