mode = "repository"
name = "crystal-extra"
repo = ["4::brave-bin",
	"4::minecraft-launcher",
	"4::multimc5"
]
urls = ["https://git.tar.black/crystal/programs/%repo%"
	"https://git.tar.black/crystal/pkgbuilds/%repo%",
	"https://git.tar.black/crystal/%repo%",
	"https://aur.archlinux.org/%repo%",
]
