[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-extra"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"aur:brave-bin",
	"aur:mullvad-vpn",
	"aur:mullvad-vpn-beta",
	"aur:mullvad-vpn-cli",
	"aur:microsoft-edge-stable-bin",
	"aur:microsoft-edge-beta-bin",
	"aur:microsoft-edge-dev-bin",
	"aur:google-chrome",
	"aur:google-chrome-beta",
	"aur:google-chrome-dev",
	"aur:ungoogled-chromium",
	"aur:jetbrains-toolbox",
	"aur:visual-studio-code-bin",
	"aur:polymc"
]

[repositories.urls]
aur = "https://aur.archlinux.org/{}"
