mode = "repository"
name = "crystal-x86_64"
repo = ["1::amethyst",
	"2::grub",
	"1::malachite",
]
urls = ["https://git.tar.black/crystal/programs/%repo%",
	"https://git.tar.black/crystal/pkgbuilds/%repo%",
	"https://git.tar.black/crystal/%repo%",
	"https://aur.archlinux.org/%repo%",
]
