mode = "repository"
name = "crystal-x86_64"
repo = [
	"1::amethyst",
	"1::jade",
	"1::jade_gui",
	"1::lapis",
	"1::malachite",
	"2::bsudo",
	"2::grub",
	"2::sudo"
]
urls = [
	"https://github.com/crystal-linux/%repo%",
	"https://github.com/crystal-linux/pkgbuilds.%repo%"
]
