[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-x86_64"
build_on_update = true

[mode.repository.signing]
enabled = true
key = ""
on_gen = true

[mode.workspace]

[repositories]
repos = [
	"crs:amethyst",
	"crs:jade",
	"crs:jade_gui",
	"crs:lapis",
	"crs:malachite",
	"pkg:bsudo",
	"pkg:grub",
	"pkg:sudo"
]

[repositories.urls]
crs = "https://github.com/crystal-linux/{}"
pkg = "https://github.com/crystal-linux/pkgbuild.{}"
