[base]
mode = "workspace"
smart_pull = true

[mode.repository]
name = ""
build_on_update = false

[mode.repository.signing]
enabled = false
key = ""
on_gen = false

[mode.workspace]

[repositories]
repos = [
	"crs:amethyst",
	"crs:branding",
	"crs:caveman",
	"crs:citrine",
	"crs:crystal-keyring",
	"crs:grub-theme",
	"crs:iso", 
	"crs:jade", 
	"crs:jade_gui",
	"crs:malachite",
	"crs:onyx",
	"crs:site",
	"crs:wallpapers",
	"pkg:base", 
	"pkg:filesystem",
	"pkg:gnome-apps-meta",
	"pkg:grub",
	"pkg:lsb-release",
	"pkg:sudo"
]

[repositories.urls]
crs = "ssh://git@github.com/crystal-linux/{}"
pkg = "ssh://git@github.com/crystal-linux/pkgbuild.{}"
